# Generated by Django 6.0.1 on 2026-02-19 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_activitylog_userprofile_delete_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TESTU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_nam', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('standar', 'Standard Use'), ('moderato', 'Moderato'), ('admi', 'Administrato')], default='standard', max_length=20)),
                ('use', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
