# Generated by Django 6.0.1 on 2026-03-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
    ]
