# Generated by Django 6.0.1 on 2026-03-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0010_remove_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='profile_images/default_pfp.png', upload_to='profile_images/'),
        ),
    ]
