# Generated by Django 6.0.1 on 2026-03-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_userprofile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='profile_images/default_pfp.svg', upload_to='profile_images/'),
        ),
    ]
